# Generated by Django 6.0.1 on 2026-02-01 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("RENT", "Rent"),
                            ("TRAVEL", "Travel"),
                            ("FITNESS", "Fitness"),
                            ("MEDICAL", "Medical"),
                            ("SALARY", "Salary"),
                            ("OTHERS", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="finance_tra_user_id_3294c0_idx"
                    ),
                    models.Index(
                        fields=["user", "type"], name="finance_tra_user_id_35643f_idx"
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="finance_tra_user_id_5b4ec6_idx",
                    ),
                ],
            },
        ),
    ]
