# Generated by Django 6.0.1 on 2026-02-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_category_monthlysummary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="anomaly_z_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="predicted_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predicted_transactions",
                to="finance.category",
            ),
        ),
    ]
